spring:
  datasource:
    url: jdbc:derby:stoneticket;create=true
    #    url: jdbc:derby:memory:stoneticket;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
  sql:
    init:
      mode: embedded
      schema-locations: classpath:database.sql
      continue-on-error: false
  web:
    resources:
      static-locations: classpath:/static/
  jersey:
    application-path: /api/