spring:
  datasource:
    url: jdbc:derby:jticketdb;user=TKT;create=true
#    url: jdbc:derby:memory:jticketdb;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 180000
      connection-timeout: 3000
  sql:
    init:
      mode: embedded
      schema-locations: classpath:derby.sql
      continue-on-error: true

springdoc:
  swagger-ui:
    path: api-doc
  api-docs:
    path: api/doc

ticket:
  sqlParams:
    SEATDETAILS: SEATDETAILS
    SEATSINEVENT: SEATSINEVENT
    SKU: SKU
