spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:26257/TKT
    driver-class-name: new org.postgresql.Driver
    username: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 3000
      max-lifetime: 180000
      connection-timeout: 3000
  sql:
    init:
      mode: always
      schema-locations: classpath:postgresql.sql
      continue-on-error: false
ticket:
  user-token:
    required: true
    path: /api/orders
    name: x-ticket-userId
  sqlParams:
    SEATDETAILS: SEATDETAILS
    SEATSINEVENT: SEATSINEVENT
    SKU: SKU
