spring:
  servlet:
    multipart: #making sure Jersey handle the multipart without conflicting with spring-boot
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  jersey:
    application-path: /api/
  datasource:
    url: jdbc:derby:stoneticket;create=true
    #    url: jdbc:derby:memory:stoneticket;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 3000
      max-lifetime: 180000
      connection-timeout: 3000
  sql:
    init:
      mode: embedded
      schema-locations: classpath:database.sql
      continue-on-error: true
crowd:
  application:
    name: stoneticket
    password: stoneticket
  server:
    url: https://crowd.intra.tontix.io/crowd
  session:
    validationinterval: 2

logging:
  level:
    org:
      springframework:
        security=DEBUG:




