spring:
  datasource:
    url: jdbc:derby:stoneticket;user=TKT;create=true
#    url: jdbc:derby:memory:stoneticket;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 3000
      max-lifetime: 180000
      connection-timeout: 3000
  sql:
    init:
      mode: embedded
      schema-locations: classpath:derby.sql
      continue-on-error: true
ticket:
  user-token:
    required: false
    path: /api/order
    name: x-ticket-userId
  sqlParams:
    SEATDETAILS: SEATDETAILS
    SEATSINEVENT: SEATSINEVENT
    SKU: SKU
