spring:
  profiles:
    default: dev
  servlet:
    multipart: #making sure Jersey handle the multipart without conflicting with spring-boot
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  jersey:
    application-path: /api/
#mybatis:
#  type-handlers-package: com.stonematrix.ticket.persist.mybatis.handlers
crowd:
  application:
    name: stoneticket
    password: stoneticket
  server:
    url: https://crowd.intra.tontix.io/crowd
  session:
    validationinterval: 30