spring:
  profiles:
    default: dev
  servlet:
    multipart: #making sure Jersey handle the multipart without conflicting with spring-boot
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  jersey:
    application-path: /api/
crowd:
  application:
    name: stoneticket
    password: stoneticket
  server:
    url: https://crowd.intra.tontix.io/crowd
  session:
    validationinterval: 30
ticket:
  user-token:
    required: true
    path: /api/orders
    name: x-ticket-userId
  jwt:
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDbZXedEyQZ1kMo
      QMtttwNqTJC0BW/+OWWACufxlw4isRib5Aup7vYEqqERKhdKsLldhHqca8eaHMuS
      IJLrr26rroZcwSlaefVnz2HjJP9602yIzy6Eg5tW4wus5fN0qljVlxSUVYwPV3uO
      IVj5JZXJBMwZDJnVCKdv4vAxaEB20YE2t+OMZb/4rMnpzKDgx7p535l4cWqgLshH
      WB3WQVQX37OBmw9gbGdRZCEoveOLEEXpWH2BcLy1noyuyO5Q0ZcflDDjioEpGVwB
      n34GVrcktVZCNmfeOZoNX8gmyBmIJ0boXro0aeiEiIIFcTsrvFwCgdQNmZx8nAyK
      G93TcCOwsn4DbNzYZsSnlwL086D+EJEzEszZCENGisuI2Vb4YzLAGDt6CaZheVdg
      WRpKJqtxtFMKoKJHiMBZRkz9+TfWsQAfJ5hBYlnOGyAaRSwG/1xKgMh4GGxXf74A
      dEHllM7nbZuwqWrNPbfHRmnOd73TDjzrH6dLXiRMTcgPHhdMReaDpLi9Wnk3zngh
      gPF7Xvu58HQSdWe6zhh+lRuTAsrHaHlETRI0EEKhRJWZEaxTlnKKSwDqBOsDIeum
      Y9NRPAMJt5YIGXGYrlOlpGAETRRh8ivVhG5Fw5TqFm02vVdU71D/jntBFlkzXuKp
      fek3mxgDl34ILfNZ1JB+uUwR3MINdwIDAQABAoICAQDTt4ANMSp2UGCwWI63CpQe
      IVLGljSz5JmBTYT0iyuV6MZxsUhcLYB1kl8qHC8r4YyPpUdY6V1N6Bm+ovaEv9+R
      hzKcEb8hU22xRtwUgWCVG6+x+hTOxd3CpAlhSOp+G+DsBQZT+pXVPDu8NYwRqeZ4
      fMukJJfSj65cd2gIla0XvCbwMdZBZvMxOzUCDHj3UWYvM8p7Ax+9Akg9KNhqKNLI
      0xP7rzHQf+vYDEM/eLc7PHHqs30xyyQgM6dZCAeKMCegzrW67q6jhZhW7J2F6mqD
      3wYlkTD8ryNtYo/YdOLGk/iGRttztvwt4TlvnQxXsUYtGTIUCbeMPF6RbEDNSHr2
      v5zPu/9epE73F7D1zbncV9gdR9lu9Q/fiWIHPjEGLbp0rSH1DIHT7NzJEUcwFrWo
      1FWyTYpKrxlQWODcTsrvp03M2at5v2xAFnzbJav6yWI40bM2I+lsJLt6rxonoxO9
      ZoJDMptYBDJrMyPUvmyV9PzGKhGLcUoB6/jGbVqTZJqv1KL4oTjFuA5UDXUBQLrq
      EIdpPkn3aGFLsrrBJwtuq0nsdsPz1YvFYj4kIoEwJ3g8TGEV9i1XYd1Id5pGfsaZ
      XIJC+SEGqSEiXZFyTfNhWHMOgBQTl11yoGDKDMGMwOcxWErRiniujnTa8wcoA6eH
      KHjg+VhOO791qBmnVqOIeQKCAQEA+7mZn70QHtVM3LHwHHW42TpsT01V1IjJj+cx
      LACXAfz73bx3/2HpM6+2mhrhLQYggPuUtx30s0tuRCfEuvHjQKA1FKF0nGn5LDxS
      8RX9ErkKcgeKFJrrjV0FDoCMgNBhn56Y7VQUxib0Rs/ub906C9QNGua0bvN6+TzX
      KNSrBxKSzKsW7fWeYjBmt0BC1MPQhC8VbsCu61LlCDh9mn0kLwiQmoXNqsFAdFBM
      mSkDT6AHLi9uIKi4887f9toH4oElYchyd6qgjDVG7hNXZ8Z+/WfCksZS5nKLOeyb
      4ZZvOP/WfhnJLKDfQiiuP0MPZQ4ZmZguyaF+qBcYR9991vmNqwKCAQEA3x9QqiqP
      K7gDpKPO5ELfjxZH861W3iDwBhYLOlxCrXUU8Nm6cYJU8H0duLsFCJE4qY7M9PEP
      kpsi4nAB5eQQNdcrFMOYudmSBt6fg/OlaPbWjdUmSLLS0rCEYSAJeLljE66tqy7A
      FDRo1y7ROgVoVdyeqnUbUiW5xINv29Xlkqi9dXjaYKwhhobFV2/FmfnjEexGp3EH
      Wc4UbXpL8gBr4gYeRXG781D6XJejnnTaFYJtAjfXXluhmvo3jmb2oYsF/SG6167N
      5ab5zLiylNVsrYN2Qx4FyS2VTU2MGxFoVdw/ogwK6yoKnUPlIrwE/cNOwXFQIJ0h
      2G3qKa6sm7R7ZQKCAQBWb9z4pQssC0JhZhh1LVdUAGPAt2WJnY7ZAyI3Ydx4qk4y
      Tc1GvHA/d07Ui/ZWZ4wxvjHKz1Z/Wp96d81uBDFst5aChw5rx1fwgKZacpp8G14i
      2cPoX2oTGKXr3OhiMyvSi7sng3++qxGmXzAY6XZNKXt2iVHb52+KtgGL27r+qroN
      3ZH6FCVWwhgDROWt+a9YNHK/nRpzY/uRXxSCQAZ0wBQne1qsD7/6MLicvyCL7v+I
      NHE0dbtMvPTa5vNeK8qSUSo9PTHz8zdv+ORClj509XQywjclOp/kPAMq62U1xWP5
      2RDjajo/lYh/4J8grD7OJxup0PKU9Zk41N15PCgRAoIBAQCJKVcNRNx+o8CZlZm5
      +OI1tBzHT+f25YioNSTx24Wh3DfjV/WlkdllfYSn61BM0/lhQsf8S7SnC3eGfBSu
      nmTYtE1nllZs6bM7ReAJ3d3xiMycpEvEpSm1G45Fpswryst9bgSVF0g9I3rPzZgR
      cwGQxu9DGnqRJV/tzl8VZYibf9/4NzMH+skhSfhGqA9xeIx+mCFXDcTXEDi+lE/b
      lSa868XwKtq/2SgPg6ix4GOwlV0t3+Ylu269NtSwVduHs08bLYEO1gb9BojJsUEW
      /Zyxjf9Fg09LPRprSyC2Ax2AqsTzeTO9HTspMnPJxovK9CWWBXKcmfwUcH1i4l55
      2ZmBAoIBAAbqNoMeS7B03vWDSeCylFsgSK5QmFWjbZVx85krmXjKhY+eA7cCUQI5
      13y5vjDhFlO5DyNoZGUFXnCqhB8cGH8Jb+RBBgEXBQZAz67mczyBoOedtuGMbDpe
      24nus+hovyGlb4AEPrLt9mZQLQ2geHPHXp4P3nvYh6QM8FT+4axfLwxYZFoFnmOv
      2Fo6ZNsL/oF5H5Zg3JJUtr6W6jyJstNhsrjEj8Z/6g9kw40iqI7BFl3DqlMjF+Ee
      AIUObikCSPueG/MuJrNoy0nqmWBfwROdLRwiyf+13zoTb29ydfaEv+YefpGOV6LK
      DXE2RCFPEtlfuIQpoOyjtRFGAdlg1OU=
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA22V3nRMkGdZDKEDLbbcD
      akyQtAVv/jllgArn8ZcOIrEYm+QLqe72BKqhESoXSrC5XYR6nGvHmhzLkiCS669u
      q66GXMEpWnn1Z89h4yT/etNsiM8uhIObVuMLrOXzdKpY1ZcUlFWMD1d7jiFY+SWV
      yQTMGQyZ1Qinb+LwMWhAdtGBNrfjjGW/+KzJ6cyg4Me6ed+ZeHFqoC7IR1gd1kFU
      F9+zgZsPYGxnUWQhKL3jixBF6Vh9gXC8tZ6MrsjuUNGXH5Qw44qBKRlcAZ9+Bla3
      JLVWQjZn3jmaDV/IJsgZiCdG6F66NGnohIiCBXE7K7xcAoHUDZmcfJwMihvd03Aj
      sLJ+A2zc2GbEp5cC9POg/hCRMxLM2QhDRorLiNlW+GMywBg7egmmYXlXYFkaSiar
      cbRTCqCiR4jAWUZM/fk31rEAHyeYQWJZzhsgGkUsBv9cSoDIeBhsV3++AHRB5ZTO
      522bsKlqzT23x0Zpzne90w486x+nS14kTE3IDx4XTEXmg6S4vVp5N854IYDxe177
      ufB0EnVnus4YfpUbkwLKx2h5RE0SNBBCoUSVmRGsU5ZyiksA6gTrAyHrpmPTUTwD
      CbeWCBlxmK5TpaRgBE0UYfIr1YRuRcOU6hZtNr1XVO9Q/457QRZZM17iqX3pN5sY
      A5d+CC3zWdSQfrlMEdzCDXcCAwEAAQ==
      -----END PUBLIC KEY-----
