@startuml
mainframe Purchasing of event ticket

actor customer
boundary paymentAgent
participant eventEndpoint
participant orderEndpoint

group get information of event with sellable seats + price
customer --> eventEndpoint: GET /events
customer --> eventEndpoint: GET /events/{eventId}
customer --> eventEndpoint: GET /events/{eventId}/sessions
customer --> eventEndpoint: GET /events/{eventId}/venue
customer --> eventEndpoint: GET /events/{eventId}/venue/svg

customer --> eventEndpoint: GET /events/{eventId}/areas
customer --> eventEndpoint: GET /events/{eventId}/areas/{areaId}
customer --> eventEndpoint: GET /events/{eventId}/areas/{areaId}/seats
customer --> eventEndpoint: GET /events/{eventId}/seats/{seatId}
customer --> eventEndpoint: GET /events/{eventId}/seats/{seatId}/pricing
end

group create order and accomplish payment [OAuth2 subject owns customer orders]
customer --> orderEndpoint: GET /orders
customer --> orderEndpoint: POST /orders
customer --> orderEndpoint: GET /orders/{orderId}
customer --> paymentAgent: Initialize Customer Payment
paymentAgent --> orderEndpoint: PATCH /orders/{orderId}
end

@enduml
