apiVersion: apps/v1
kind: Deployment
metadata:
  name: jticket
  namespace: jticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jticket
  template:
    metadata:
      name: jticket
      labels:
        app: jticket
    spec:
      containers:
        - name: jticket
          image: jticket/jticket-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      restartPolicy: Always
