apiVersion: v1
kind: Service
metadata:
  name: jticket-db
  namespace: jticket
spec:
  clusterIP: None  # Headless service for DNS-based discovery
  publishNotReadyAddresses: true
  selector:
    cockroach-cluster: jticket-db
  ports:
    - name: sql
      port: 26257
      targetPort: sql
    - name: db-console
      port: 8081
      targetPort: db-console
