apiVersion: v1
kind: Service
metadata:
  name: stoneticket
  namespace: tontix
spec:
  selector:
    app: stoneticket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP